### ISSUE TITLE
2장. JPA 시작

### ISSUE THREAD

**Issue by LangVE** [daybreak6/jpa-getting-start#2]

**Comment by LangVE** [comment]
h2 실행 혹은 접속이 잘 안된다는 분이 계셨는데ㅠㅠ
저는 다행히 통과 되었습니다. 😄
(환경은 windows10 에서 설치했어요. 맥에서 하려고 했는데 왜.. windows pc에 설치했을까요;;)

![image](https://user-images.githubusercontent.com/24932090/70730076-af59c180-1d47-11ea-8a50-5e41f2daaf6e.png)


![image](https://user-images.githubusercontent.com/24932090/70729901-5db13700-1d47-11ea-806d-ceab5adb2cb2.png)

User Home 폴더에 아래같은 파일을 생성하네요.

![image](https://user-images.githubusercontent.com/24932090/70730513-7706b300-1d48-11ea-9bbd-0fcf23943430.png)

**Comment by kaiwind7** [comment]
h2 설치 후 접속이 안되다가 삭제 후 재설치를 해보니 정상적으로 됩니다.
차이를 생각해 보니 처음에는 용량 문제로 E 드라이브에 설치했고, 다음에는 그냥 C에 설치..
설치 경로에 따른 권한 문제로 보여지네요.

삭제 후 처음과 같이 E에 설치해 보니
![image](https://user-images.githubusercontent.com/51537469/71107343-415c4100-2204-11ea-808e-2b60cbef60e9.png)
메세지와 함께 연결이 안되네요..

**Comment by LangVE** [comment]
@kaiwind7 그런 문제가 있을수 있겠네요! 원인을 찾으셨다니 다행이네요~

**Comment by LangVE** [comment]
*JPQL* 코드인데요. 엔티티 객체를 대상으로 쿼리한다고 나와있는데요.  
그런탓인지 from 절에 엔티티 객체명과 동일한 UpperCamelCase를 사용하네요!  

![image](https://user-images.githubusercontent.com/24932090/71187051-a9249180-22c1-11ea-96aa-c59c287b827a.png)

무심코 소문자로 타이핑 해보았더니.. 
다음과 같은 에러 메세지를 보았습니다. 😂 

![image](https://user-images.githubusercontent.com/24932090/71187442-7333dd00-22c2-11ea-8378-4db4faa832be.png)

**Comment by kaiwind7** [comment]
혹시 마리아DB 사용하실분을 위해 설정 정보 남겨봅니다.

dependency 추가
![image](https://user-images.githubusercontent.com/51537469/71194430-3a4e3500-22cf-11ea-8d1a-34e28ea5e080.png)

persistence.xml 추가
![image](https://user-images.githubusercontent.com/51537469/71194520-6ec1f100-22cf-11ea-818d-d7186a60b7b5.png)

마리아DB(또는 mysql) 에서 JPA 테스트 하면서 한글을 insert  하는 경우 에러하는듯합니다.
인코딩 문제로 해당 테이블의 인코딩 정보를 변경해 줘야 합니다.

ALTER TABLE menu
	COLLATE='utf8mb4_general_ci',
	CONVERT TO CHARSET utf8mb4;
